# Generated by Django 5.1.4 on 2024-12-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_funcionario_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionario",
            name="CPF",
        ),
        migrations.AddField(
            model_name="funcionario",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
