# Generated by Django 5.1.4 on 2024-12-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_funcionario_cpf_funcionario_cpf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionario",
            old_name="remuneração",
            new_name="remuneracão",
        ),
    ]
