# Generated by Django 5.1.4 on 2024-12-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_remuneração_funcionario_remuneracão"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionario",
            old_name="remuneracão",
            new_name="remuneracao",
        ),
    ]
