# Generated by Django 5.1.4 on 2024-12-21 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_remuneracão_funcionario_remuneracao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionario",
            old_name="data_nascimento",
            new_name="bithday_date",
        ),
        migrations.RenameField(
            model_name="funcionario",
            old_name="nome",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="funcionario",
            old_name="remuneracao",
            new_name="salary",
        ),
    ]
