# Generated by Django 5.1.4 on 2024-12-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_data_nascimento_funcionario_bithday_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionario",
            old_name="bithday_date",
            new_name="birthday_date",
        ),
    ]
